### ISSUE TITLE
Change how staking is handled in runtime

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#1407]
Currently there is a bug in staking caused by the mismatch between when the validator proposal gets processed and when the account is updated. More specifically, when a valid staking transaction is received, the runtime will update the account immediately (because `signer_id` is the same as `receipt_id`) but the validator proposal the transaction produces will be included in the next block and thus will only be processed when the next block is processed. Such mismatch leads to a potential staking invariant failure if a staking transaction is sent in the last block of an epoch.

To address this, I propose that we add a new action `StakeAccountUpdate` that is generated when a stake action is processed whose sole purpose is to update the account. Then the `Stake` action receipt will only update validator proposals. Since this receipt will be processed in the next block, the mismatch is resolved.

**Comment by evgenykuzyakov** [comment]
I understand the issue, but a proposed solution has issues as well.

There is no guarantee that the receipt for `StakeAccountUpdate` would be processed in the next block which would lead to invariant failure as well.

Currently `.staked` under account is handled in multiple places:
- when Runtime processes `Stake` action, the `.staked` is updated. You propose we move it to `StakeAccountUpdate` action, but it would lead to a state of the account where the money is taken, but the actual staked amount is not updated yet. So if there is a 2nd `Stake` action for the same account is processed before `StakeAccountUpdate` it would use inconsistent information.
- when validators receive rewards or getting unstaked/kicked out.

There is no easy solution to the issue because the account have balance in 3 states:
- non-staked
- pending-staked
- actually-staked

**Comment by bowenwang1996** [comment]
It is fine if `StakeAccountUpdate` is not processed in the next block. This happens when the chunk is not produced, in which case the proposals also do not get included in the block header. Also, the stake action will not update the account. Both `amount` and `staked` will be updated when we process `StakeAccountUpdate`

**Comment by evgenykuzyakov** [comment]
> Both `amount` and `staked` will be updated when we process `StakeAccountUpdate`.

So I can double spent and stake at the same time.

**Comment by bowenwang1996** [comment]
Good point. Looks like changing runtime is not an option.

**Comment by evgenykuzyakov** [comment]
I don't think we should close this issue. Just change the approach.
Side issue: it seems you can blow up Block Header by generating million of stake proposals right now from one account, so it should be addressed as well.

Here is what we want:
- When we process `validator_proposals` in the chain, they should all be valid. Meaning no check for account balance needed, they are paid already and this balance can't be double-spent.
- Runtime needs to know the latest proposed stake balance per account to properly generate new validator proposals for new stake actions.
- You shouldn't be able to delete account that proposed a staking or currently staking.

**Comment by bowenwang1996** [comment]
We did change the approach and the new one does not require modifying runtime. Why can you blow up block headers? At the very least block has size limit.

**Comment by evgenykuzyakov** [comment]
You're right, there are actually no easy way to prevent it without enforcing something like 1 stake per account per epoch.
But at least we can aggregate proposals per account (in case we don't do this) per block.

> We did change the approach and the new one does not require modifying runtime. 

Can you explain it here. Cause I don't see an easy fix because there are conflicting operations between chain and runtime on `.staked` field.

**Comment by bowenwang1996** [comment]
When finalizing an epoch, we also include the validator proposals included in the first block of next epoch.

**Comment by evgenykuzyakov** [comment]
i see. And for the next block (the first in the epoch), you don't include them I assume

**Comment by bowenwang1996** [comment]
Yes. The proposals in the first block of an epoch actually come from the last epoch so should be counted towards the last epoch.
