### ISSUE TITLE
track_shards test is flaky

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1441]
This test is failing repeatedly on the PR that did not change any code relevant to it:
https://gitlab.com/near-protocol/nearcore/-/jobs/317981263 
https://github.com/nearprotocol/nearcore/pull/1440

I am not sure what has triggered the flakiness.

**Comment by ailisp** [comment]
We have some of tests, this is one of them, frequently fail because of timeout. I'm in process of using gitlab shell runner to replace gitlab docker runner, which should strictly faster and close to local cargo test. (Had run test_cargo job in a local gitlab runner, no cache, shell runner takes ~17 minutes, docker runner ~22 minutes. Build time doesn't differ a lot, so it's likely shell runner will take less time to run integration tests and less timeout)

**Comment by ailisp** [comment]
This is a more unfortunate example: https://github.com/nearprotocol/nearcore/pull/1401 i just try to replace master ci with staging ci, yet everytime it fails because some test time out.

**Comment by nearmax** [comment]
Our CI flakiness makes it really hard to make even simple no-op changes: https://gitlab.com/near-protocol/nearcore/-/jobs/318785769

**Comment by ailisp** [comment]
This specific test isn't flaky after moving to shell runner. Another somtimes flaky case `thread panicked while panicking` is tracked in #1426
