### ISSUE TITLE
[Discussion] State parts and runtime

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1447]
This https://github.com/nearprotocol/nearcore/pull/1430/ introduced a debatable change to the runtime.
* It breaks an important invariant of the runtime: runtime should be oblivious of how storage operates, e.g. how do we fetch it, whether we have a full state or just parts of it.
* It adds magic numbers here: https://github.com/nearprotocol/nearcore/pull/1430/files#diff-ea1fbbac017ef3f0a46bcd78c2ade930R847

This code should be abstracted out in `core/store`.

**Comment by nearmax** [comment]
Now I see that it is properly hidden with https://github.com/nearprotocol/nearcore/pull/1444. Closing.

**Comment by Kouprin** [comment]
The number of parts the state is divided depends completely on the chosen runtime.
Each piece of state is also completely dependent on the way we choose to split the state.

The problem is - something should be responsible for splitting the state, proofing parts and to understand how to do it in a proper way. I expect the good idea is to delegate this to RuntimeAdapter with methods `obtain_state_part`, `accept_state_part` and `confirm_state`.

At the same time, network should work independently to the way we choose to process the state. It needs to take somehow proven (and proofable) value of number of parts oblivious of inner runtime implementation.

So, the number of parts is the same important state data as a state hash. In #1444 I've hidden it into StateRoot struct. It may help to ignore the number of parts in most cases, I hope.

**Comment by nearmax** [comment]
I am renaming this issue to the discussion and re-opening it.

To clarify, there is a naming confusion of what we call a "runtime". There is A) `runtime` folder in `nearcore`; B) and there is `near/src/runtime.rs`+`RuntimeAdapter`. I am suggesting to keep any notion of parts from (A). Encapsulating them in `StateRoot` sounds reasonable.

> The number of parts the state is divided depends completely on the chosen runtime.

By chosen runtime, you mean whatever implements `RuntimeAdapter`?  Why would we want to have number of parts depend on it? Isn't the whole point of parts is to partition the trie so that we can fetch it from multiple nodes in parts, why would we want the partitioning of the trie to depend on anything but the content of the trie?

> The problem is - something should be responsible for splitting the state, proofing parts and to understand how to do it in a proper way.

Why won't we implement it on `core/store` level? We can have the trie to implement `obtain_state_part`, `accept_state_part` and `confirm_state`. Also we can have the trie tell exactly how it needs to be partitioned. We let trie determine exactly what the state hash is, so why won't we let trie determine what parts are? We even keep these things now in `StateRoot` together.

**Comment by Kouprin** [comment]
@nearmax thank you for clarification! I've read what you wrote several times and I have no fundamental disagreements. Sorry for confusing you, I mean storage and core as a part of Runtime.

Related to my task, I operate the following levels of abstraction:
1) Network level.
2) Chain / Client level.
3) Runtime Adapter. It's a bridge between Chain / Client and Runtime.
4) Runtime, which encapsulates all the system details, including the way of storing data. At least, we have two different Runtimes for now, I call in KV (key-value in test utils) and Nightshade.

I assume that nothing but Runtime knows better how to split the State perfectly. I mean no one can say reasonably: "hey, divide this thing into 50 parts". That's why I expect it's better to use Runtime Adapter interface to get the best way of dividing from the chosen Runtime (which is not limited to be trie).

The same idea with proofing parts. Nothing can do in at Client side because Client even have no clue which Runtime works for him. The solution is to delegate proofing parts thru Runtime Adapter to Runtime - and then Runtime can decide itself what module or piece of code should complete this job.

Technically, I even didn't introduce anything new into Runtime Adapter. There already were methods `dump_state` and `set_state`. I've adapted them to the case of having many parts.

**Comment by nearmax** [comment]
> I assume that nothing but Runtime knows better how to split the State perfectly. I mean no one can say reasonably: "hey, divide this thing into 50 parts".

It seems like the trie itself can tell exactly how it needs to be split, without involving a runtime. Just based on its size, using some dynamic programming, it could decide the separation into subtries of equal sizes. I still have a hard time understanding what Runtime Adapter would add to this? The trie is the data structure that stores the data, while Runtime just performs operations on this data structure. Why would we need anything but the data structure itself to determine how to split it into parts?

**Comment by Kouprin** [comment]
What exactly confuses you? Could you please point directly?

I can't understand clearly what I need to argue.

**Comment by Kouprin** [comment]
Is it about methods in Runtime Adapter or what?

**Comment by nearmax** [comment]
Discussed offline. @Kouprin explained that he would implement `obtain_state_part`, `accept_state_part` and `confirm_state` in the `RuntimeAdapter` trait and these methods would directly access `Trie`.
