### ISSUE TITLE
Fix AccessKeyPermission checks

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1454]
This issue contains two things: a bug report and a feature request.

**Bug report**
It seems like as long as the action is not a function call we allow it to be performed with any access key as long as the sender id equals the account id. This means the only advantage of the full access key over not full access key is that full access key can call any contract method, while not full access key cannot. This has two issues:
* We cannot have accounts that completely give away control of them by removing full access keys and keeping non-full access keys only. This is required for https://github.com/nearprotocol/NEPs/pull/19
* If a non-full access key can redeploy smart contract and move assets then it has significant control over the account. I do not think this is intended and therefore this is reported as a bug.

**Feature request**
Every action should have an associated system function name, e.g. `Action::CreateAccount` -> `_create_account`. We then can allow/disallow non-full access keys to perform certain actions on the account. We then should also remove checks `actor_id != account_id`, like this one here: https://github.com/nearprotocol/nearcore/blob/b34e15c1157d9002a784b2d35d84b7bbff186b55/runtime/runtime/src/actions.rs#L360

Note, the underscore will help us prevent the name collision in case the contract has a method `create_account`, because contract methods are not allowed to start with an underscore.

**Comment by nearmax** [comment]
Added @fckt in case he is interested in fixing it.

**Comment by fckt** [comment]
I'm going to check the code, but I have an ad-hock question: by `_create_account ` you mean some function in associated contract (if so, which one)?

**Comment by evgenykuzyakov** [comment]
So for the security part of this issue, we do have a check there:
https://github.com/nearprotocol/nearcore/blob/staging/runtime/runtime/src/lib.rs#L248-L254

As for the automatic actions, we'll need to decide on the naming, serialization and format. It's completely doable right now through the contract and runtime promise APIs, and it doesn't require any custom Runtime modifications. So from the simplicity and security consideration the current option is the best. We're currently missing the ability to buy more gas from the contract, but it should be added in the future.
As discussed offline, the contract size increase and duplicated code concern should be addressed by itself, instead of changing the access key permission.

The best option to support custom action permissions is to create a new access key permission and expose actions and config there, but it's a big change and needs to have strong motivation.

**Comment by nearmax** [comment]
Discussed with @evgenykuzyakov  offline:

Regarding bug. It seems to be okay, I just missed the following line of code: https://github.com/nearprotocol/nearcore/blob/01be3bbf8961fb6b8d370c9d1c0c571d4e468b04/runtime/runtime/src/lib.rs#L274

Regarding feature. @evgenykuzyakov suggested that we do not implement it yet, because it would increase the complexity. Instead when contract developer wants to have access keys that can, e.g. add another access key, they create a contract method, e.g. `add_access_key` that simply issues a transaction to itself to create an access key.
