### ISSUE TITLE
Delete old states

### ISSUE THREAD

**Issue by mikhailOK** [nearprotocol/nearcore#1648]
`ApplyTransactionResult` has `TrieChanges` which has a set of insertions to store the new state and deletions to remove the old state (see doc comment for the class). We never apply deletions so the storage has all versions of the state.
We should delete old states and states from discarded forks.
To do that we need to keep `TrieChanges` of recent blocks and have logic for deleting state versions we don't need.

**Comment by ilblackdragon** [comment]
@Kouprin @bowenwang1996 please grab this issue for whoever is working on this.

**Comment by Kouprin** [comment]
For now, we keep old state parts forever while syncing. We should clear old parts from store (keys are: ColStateParts, ColStateHeaders).
@mikhailOK @ilblackdragon I didn't how `TrieChanges ` and `ApplyTransactionResult` are relevant to old states deleting. If there are different tasks, please reassign me to what I was pointed above.

**Comment by Kouprin** [comment]
Discussed with @nearmax offline.
At epoch changing, we download a fresh state completely with no removed nodes. This means, for GCing old state it's enough to get rid of old state completely. GC will happen automatically while epoch changing. At current implementation of State Sync we re-download all the state anyway.
Implementation of decreasing number of links in persistent trie is relevant to Continuous State Sync (https://github.com/nearprotocol/nearcore/issues/2060) and will be done when become actual.

**Comment by Kouprin** [comment]
+ check `clear_downloaded_parts`

**Comment by nearmax** [comment]
Discussed this issue with @ilblackdragon and @Kouprin more. We are going to have nodes that track most or all shards which means they will be continuously validating them non-stop. This means that state syncing will not clean up their cache.

Regarding the `TrieChanges`. I don't think we should be following this approach:
> To do that we need to keep `TrieChanges` of recent blocks and have logic for deleting state versions we don't need.

It is better to implement careful node counting which will allow us to do this and other things, for instance pruning of intermediate blocks (this will be useful for the archival nodes that our custodies are going to be running). For instance pruning every fifth block so that when someone requests state through RPC we can compute it from the closest non-pruned block.

**Comment by Kouprin** [comment]
@nearmax,
discussed with @mikhailOK, it seems we can revert insertions to remove old states from trie
check https://github.com/nearprotocol/nearcore/pull/2084 for implementation details

**Comment by ilblackdragon** [comment]
@Kouprin what is the status for this after work on GC you have done already?

**Comment by Kouprin** [comment]
> @Kouprin what is the status for this after work on GC you have done already?

@mikhailOK's review on https://github.com/nearprotocol/nearcore/pull/2084 is critical
then we merge that PR to master and close the issue as done
