### ISSUE TITLE
Handling account id from multiple nodes.

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#1694]
Right now each account id is associated with exactly one peer id. This implies that all traffic going to this account id, is routed to the peer id. Is it possible that an honest node want to manage one account id from multiple nodes? Notice in this case by manage we are referring to receive all packages directed to this account.

Some situations when this is valuable:
- An honest entity wants to ditch a peer_id for whatever reason (it lost access, there was a problem with keys, it got banned) and one to associate its old account id to a new peer id.
- A whale wants to manage a single validator account from different nodes.

**Comment by SkidanovAlex** [comment]
There's no plan to support such a scenario in any foreseeable future, because running multiple nodes with the same account needs to carefully handle which nodes create blocks, which is a non-trivial task.

So let's keep one account = one peer.
Need to make sure though that if one rejoins the network with a new peer-id, but the same account, it works.
