### ISSUE TITLE
Execution reward for contract owner

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#1704]
Right now in runtime we reward 30% of gas fee of execution of every transaction to the receiver of the transaction. However, the intention is to give reward to contracts so that developers of the contract can receive some reward by developing the contract. Therefore I suggest we only give this reward if the action is of type function `FunctionCall`.

**Comment by evgenykuzyakov** [comment]
@nearmax What do you think?

The reason it was done before to give 30% for everything is because the Runtime didn't provide the total validator_reward value, so it was hard to account which gas was rewarded to the account and which was not. But now we do provide the total validator reward, so we can properly account for the gas burnt only by contract execution.
So I suggest we fix it and only reward 30% for function call actions.

**Comment by nearmax** [comment]
I agree.

**Comment by nearmax** [comment]
@bowenwang1996 This is fully implemented, correct?

**Comment by bowenwang1996** [comment]
Yes
