### ISSUE TITLE
AccessKeyPermission type for staking transactions

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1759]
Use cases:
 - I'm running a node and the node only has staking key. I want to automatically stake when get kicked out (or even programmatically adjust the amount of stake).
 - I'm have a delegation smart contract, and we only want to allow to send staking transactions on it.

This is doable with smart contracts, but becomes hard to audit and also will clash with our lockup contracts.

Implementation details:
 - Add new `AccessKeyPermission` for `Staking`, that allows to sign staking transaction with such key.

Now, at `stake` from near-shell, we can (by default?) not only send `StakeAction` but also `AddKeyAction` with the same key and `Staking` permission.
Later we can add a flag to the node to allow to automatically re-send staking transaction using the `validator_key` if validator wants.

**Comment by bowenwang1996** [comment]
Why not add the stake key to the account directly when the staking action is processed?

**Comment by nearmax** [comment]
Discussed offline. For lockup contracts we don't need to add a separate access key type, the contracts can easily have their code extended to support staking-only keys.

In general, if we want to have such functionality outside the smart contract then I think we should extend the access key itself instead of modifying the `Staking` transaction. I propose that we change [AccessKeyPermission]() to be a struct like this:

```rust
struct AccessKeyPermission {
  create_account: AccessType<()>,
  deploy_contract: AccessType<()>,
  function_call: AccessType<FunctionCallPermission>,
  transfer: AccessType<()>,
  stake: AccessType<()>,
  add_key: AccessType<()>,
  delete_key: AccessType<()>,
  delete_account: AccessType<()>
}
```

```rust
struct AccessType<T> {
  None,
  Full,
  Restricted(T)
}
```

This will allow forward compatibility in case we decide to promote some of `AccessType<()>` to something more complex while being able to deserialize old binary records using new rust structures. @ilblackdragon @evgenykuzyakov WDYT?

**Comment by nearmax** [comment]
@ilblackdragon We have decided to not pursue this path, correct?

**Comment by ilblackdragon** [comment]
Closing this.
