### ISSUE TITLE
Unexpected error msgs in state_sync

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#1824]
`cargo test --color=always --all-features --package near --test sync_state_nodes sync_empty_state -- --exact --nocapture`

Test passes but with state sync error messages:
```
[2019-12-05T11:35:07Z ERROR near_client::sync] State sync: state download for shard 0 timed out in 10 seconds
[2019-12-05T11:35:07Z ERROR near_client::sync] State sync: state download for shard 1 timed out in 10 seconds
[2019-12-05T11:35:07Z ERROR near_client::sync] State sync: state download for shard 2 timed out in 10 seconds
[2019-12-05T11:35:07Z ERROR near_client::sync] State sync: state download for shard 3 timed out in 10 seconds
```
Appeared after commit `a5ab748f3484b19112932ac63fa72917e47ee2ce` but NOT related to it.
The problem is that `NetworkRequests::StateRequest` doesn't reach requested target.

**Comment by Kouprin** [comment]
It is `network_adapter.send(NetworkRequests::StateRequest)` issue. Not related to State Sync.
Reproducing steps:
1. In StateSync::request_shard() find the code which calls `self.network_adapter.send()`
<img width="730" alt="Screenshot 2019-12-09 at 19 57 37" src="https://user-images.githubusercontent.com/5685493/70455949-3ac02200-1abe-11ea-87c8-14fad09332f1.png">
2. In ClientActor::handle() find the code which processes `NetworkClientMessages::StateRequest()`
<img width="1031" alt="Screenshot 2019-12-09 at 19 59 05" src="https://user-images.githubusercontent.com/5685493/70456054-72c76500-1abe-11ea-8df5-1106d71ac744.png">
Expected output: lines started with "???" after lines started with "!!!"
<img width="682" alt="Screenshot 2019-12-09 at 20 04 35" src="https://user-images.githubusercontent.com/5685493/70456445-26c8f000-1abf-11ea-9bbb-b93d633fc4b7.png">
Current output: lines started with "!!!" only, then timeout, then expected one
<img width="660" alt="Screenshot 2019-12-09 at 20 04 05" src="https://user-images.githubusercontent.com/5685493/70456395-1284f300-1abf-11ea-99bb-a6bbfd643bcb.png">

**Comment by bowenwang1996** [comment]
looks like it is not propagated through the network. @mfornet can you take a look?

**Comment by Kouprin** [comment]
Appeared because of https://github.com/nearprotocol/nearcore/pull/1806.

**Comment by Kouprin** [comment]
I investigated the situation more carefully.
It's NOT related to `a5ab748f3484b19112932ac63fa72917e47ee2ce` but appears after
```
+                        } else if &block.hash() == sync_hash {
+                            self.client.chain.save_orphan(&block);
+                            return NetworkClientResponses::NoResponse;
```
It's definitely NOT related to State Sync.

**Comment by mfornet** [comment]
@Kouprin The problem with this test is that the `node2` start to fetch state too fast, before receiving announce account from `node1`, so `RequestState` message is dropped.

The current policy about message targeted to non existent peers/account in the routing table is dropping them, though we can do something smarter such as storing this messages in a temporary cache and if we discover route to this peer we send it.

**Comment by Kouprin** [comment]
@mfornet to make sure: node `test2` takes `runtime_adapter.get_epoch_block_producers()` and knows there should be `test1` who should be able to give a state. That's why `test2` calls `network_adapter.send(NetworkRequests::StateRequest)` with target = `test1`. But the message is dropped because network doesn't know about `test1`, right?

**Comment by mfornet** [comment]
Yes, that is exactly what is happening, in practice this is happening right now because both nodes know each other from genesis, otherwise this situation shouldn't happen with healthy nodes. This is, it is not supposed that a node become a validator without us having a route to them (unless we know it from genesis).

**Comment by Kouprin** [comment]
@mfornet what you suggest here? Is it enough to write a comment in the test that it's expected to get a timeout error?

**Comment by mfornet** [comment]
Well from network pov nothing unexpected is happening, but the message log is misleading since it is waiting for something that we know for sure it is not happening, since the message was dropped in our side. 

Maybe we can try to propagate the error back to the original sender and retry after some time or log different error if message couldn't be delivered. This message make us believe that we didn't receive response, when in reality we didn't even send request.

I can put in place a mechanism that send message as soon as routes to target are met, but as matter of fact I think at protocol level you should assume messages can be dropped and protocol should still work fine.

**Comment by bowenwang1996** [comment]
But I thought it is dropped because there is no route to the peer? Is that an expected behavior?

**Comment by mfornet** [comment]
There is no route to the peer! It just happens that a node knows that there should be certain account on the network (from genesis file) but it still doesn't know route to it. Message is misleading because the message is dropped on the side of the sender, so client is waiting for a message the certainly will not arrive.

**Comment by Kouprin** [comment]
I think what's happening now is: StateSync sends a request `NetworkRequests::StateRequest` to unknown peer and waits until timeout happens. After that, StateSync sends a request again and it works (because peer appears between requests).

How it should be:
1. StateSync should be unable to send a request to unknown peer. Can we remove `runtime_adapter.get_epoch_block_producers` from possible targets in StateSync::request_shard easily? @bowenwang1996 Can it help?
2. StateSync should receive a message from network that request didn't send and set DownloadStatus.error true. It causes sending `NetworkRequests::StateRequest` on the very next iteration, without waiting until timeout. How can we propagate back a message to StateSync? @mfornet Could you add `NetworkClientMessages::StateRequestError` or kinda like that to `NetworkClientMessages`? I can process it in `ClientActor::handle` then.

**Comment by SkidanovAlex** [comment]
> Can we remove runtime_adapter.get_epoch_block_producers

You cannot remove it. If you don't have peers that are aware of some shard, you won't be able to fetch the state at all.
