### ISSUE TITLE
RPC: Some RPC are not processed by the devnet.

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#200]
Seems the logic is random and it's hard to reproduce consistently.
But even simple "/scripts/rpc.py send_money -s bob -r alice -a 3" fails some times to generate a block on devnet

**Comment by bowenwang1996** [comment]
Upon closer inspection, the bug occurs here https://github.com/nearprotocol/nearcore/blob/b40dae41c58017923f4b89774f0eba24223d021c/node/cli/src/test_utils.rs#L28. Sometimes the body does not go through.

**Comment by nearmax** [comment]
I'll take a look.

**Comment by nearmax** [comment]
An update. I noticed it is not a specific channel that gets stuck. Sometimes it is the channel that sends transactions from RPC to the fake consensus (more frequent). Sometimes it is the channel that sends consensus from the fake consensus to the block producer.
I read documentation on channels and there is nothing that would explain such behavior.

My current working hypothesis is that our RPC server that we yanked from parity is somehow interfering with the tokio loop in which we are running it.
I also haven't observed such behavior when I was testing TxFlow on channels that were faking the network.

**Comment by nearmax** [comment]
I think I understand now what is happening with the said bug. JsonRPC spawns its own loop thread inside the RPC server which becomes nested in our loop thread. This in turn interferes with the ability of our loop thread to know when certain futures are ready (because readiness notification only works within one thread loop). As the result our thread loop does not know when some stuff is in the channel. Sometimes though it is lucky to poll it and get the stuff from it.

**Comment by azban** [comment]
yea TARPC, definitely looked preferable when i was looking into RPC implementations but there really isn't much out there for JSON-RPC in rust unfortunately. you said you have a potential fix?

**Comment by nearmax** [comment]
Three potential fixes that I tried:
1) Injecting JsonRPC with our own loop executor. Their implementation of JsonRPC allows it to be injectable with `event_loop_executor()` function. However when I try doing it even though the service looks to running it does not listen on the port anymore.

2) Taking whatever loop executor JsonRPC is using and run our stuff on it. Same result -- the service does not listen on the port anymore.

3) Using `std::sync::mpsc` instead of `futures::sync::mpsc` for sending transactions from rpc to fake consensus, because the former uses a mechanism that does not depend on the readiness of the futures. This however does not fix the problem, so I am suspecting that either: a) JsonRPC interferes with our async loop mechanism more than I thought; b) It is not JsonRPC.

I'll run some experiments to verify that it is JsonRPC. If it is then I suggest we consider some simple Http server instead of JsonRPC since we don't really need the RPC part.

**Comment by nearmax** [comment]
### Found cause
There are several factors at play.

* JsonRPC is to blame for messages being not delivered through the channels. JsonRPC starts its own event loops. However if we have a channel that has sender in one loop and receiver in another loop, the other loop will not be notified when the object gets into the sender. Unfortunately, even though JsonRPC has API for injecting and/or reusing executors it does not seem to work, see (1) and (2) from above.
    * The issue with JsonRPC is hard to workaround, because we cannot use tokio channels to communicate between JsonRPC and the rest of the infra. Using `std::sync::mpsc` channels however  creates another problem when tasks execute blocking wait on the receiver are blocking the entire worker of the loop which brings another set of the consequences.
    * JsonRPC calls tokio internals through deprecated API, that might be a part of the issue.

* Our integration tests should not assume that transaction is executed immediately after it was sent. The correct way to test the contract deployment should be:
    1. Issue a contract creation transaction
    2. Wait in a loop for this transaction to propagate by calling a view call. If the integration test is running in the same loop with the node, the loop should be implemented using tokio `Interval` and not standard `loop + thread:sleep`.
    3. Submit contract deployment transaction.
    4. Wait for it to complete in a loop.

### Solution

* JsonRPC should be replaced with a standard Http server that does not spawn its own threads, but is instead hosted on our loop.

* Our integration tests should be using explicit waiting mechanism to ensure that transactions were processed.

* Our code should be avoiding blocking stuff, like blocking channels.

**Comment by nearmax** [comment]
For the record, the following code demonstrates that without JsonRPC, blocking channels, and with some waiting on transaction completion, the contract deployment consistently goes through.

* Navigate to branch https://github.com/nearprotocol/nearcore/tree/fixing_rpc_3

* Then from the root run ~20 times
```
rm -r storage; cargo run --package=devnet
```

* Observe that no error message is printed.

**Comment by nearmax** [comment]
Relevant: https://github.com/tokio-rs/tokio-core/issues/167

**Comment by nearmax** [comment]
You are right, for that specific way of writing an integration test it should not be an issue. However we should still verify that account creation propagated before we send contract deployment.
