### ISSUE TITLE
State sync should happen only on epochs frontier

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#2021]
Check BLOCK_FETCH_HORIZON.

**Comment by Kouprin** [comment]
May affect https://github.com/nearprotocol/nearcore/issues/1047.

**Comment by Kouprin** [comment]
@bowenwang1996 @SkidanovAlex please discuss about rationale here.

**Comment by SkidanovAlex** [comment]
The biggest rationale is that if we always state sync from the epoch boundary, then we can later add optimizations on the end of the node that serves the state to precompute some responses and not recompute them every time (since at any given point there will be only ~2 hashes from which syncs are likely). The node can even chose to reject state sync from other than the recent couple epoch starts.

Also designing some components might get easier. E.g. in randomness today it is very desirable for me that a block producer that creates a block in some epoch processed all the preceding blocks in the same epoch. With state sync on epoch boundaries this is guaranteed to be the case.

**Comment by bowenwang1996** [comment]
Sounds good. My only concern is that since an epoch can be pretty long and we do orphan sync back to `sync_hash` there can be much more traffic involved.

**Comment by ilblackdragon** [comment]
@SkidanovAlex rational of "might get easier" seems a huge stretch for (a) change (b) huge slow down to sync. I agree that having some checkpoints is better to sync from, but that seems like a future problem.
Current problem is things like #2380 .

Also there 0 considerations for Epoch Manager from this - it doesn't rely on state or blocks in any way, and only requires block headers.

**Comment by SkidanovAlex** [comment]
Reverting the change will hide the problem with long block sync, not solve it.
State sync in practice will be taking on the order of hours, and fetching tens of thousands of blocks will be required anyway.

**Comment by bowenwang1996** [comment]
@ilblackdragon @SkidanovAlex Is there any reason to keep this issue open? I think we can close it in favor of #2380.
