### ISSUE TITLE
expose balance-change events in a block

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2036]
For a given block, we can query for each account the events that happen in that block, but there is no way to query all the events that change account balances for all the accounts that are touched in the block.

**Comment by frol** [comment]
Since #2253 there is a new RPC endpoint to query a list of accounts with a type of the state change (e.g. `account_touched`) touched within a given block.

Since #2148 the `changes` RPC exposes detailed information about the state change (a cause and a new value).

#2264 will allow querying RPC for state changes of the same type (e.g. `account_changes`) for a list of `account_id`s.

@bowenwang1996 Do those PRs resolve this issue? Is there anything extra we want to expose?

**Comment by bowenwang1996** [comment]
I believe it's sufficient.
