### ISSUE TITLE
Allow querying accounts touched within the block

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2128]
We should extend RPC API to query all accounts that were touched within the given block.

**Comment by frol** [comment]
The implementation is already there, `account_id` that is specified is used as a prefix, so passing an empty `account_id` works as one requested in this issue. This is definitely unexpected, so I will work on the design a little bit more, and make this feature clear especially since it is not really expected to receive info about changes to vlad, vlad111 and vlad222 accounts when you specify `vlad` as `account_id` and expect only the exact match to be filtered.

**Comment by frol** [comment]
I was under a wrong impression there. Well, it was a bug turning as a feature. I will need to implement a new RPC endpoint exposing a list of account IDs touched in a block.

Draft API:

```
$ http post http://localhost:3030 jsonrpc=2.0 id=dontcare \
    method=EXPERIMENTAL_changes_list_accounts \
    'params:={"block_id": "DYHRzRbxUR1ANPdCQcgQE9g5zyYQoDZ1k8BJEQ3hDSgW"}'
```

```
$ http post http://localhost:3030 jsonrpc=2.0 id=dontcare \
    method=EXPERIMENTAL_changes_list_accounts \
    'params:={"block_id": 100500}'
```

```
$ http post http://localhost:3030 jsonrpc=2.0 id=dontcare \
    method=EXPERIMENTAL_changes_list_accounts \
    'params:={"finality": "latest"}'
```

NOTE: The endpoint naming needs some bikeshedding.

The response:

```js
{
    "block_hash": "DYHRzRbxUR1ANPdCQcgQE9g5zyYQoDZ1k8BJEQ3hDSgW",
    "changes": [
        {
            "account_id": "frol.near",
            "type": "data_changes",
        },
        {
            "account_id": "frol.near",
            "type": "account_changes",
        },
        {
            "account_id": "user.near",
            "type": "access_key_changes",
        },
    ]
}
```

**Comment by frol** [comment]
The follow-up documentation request is https://github.com/nearprotocol/docs/issues/267
