### ISSUE TITLE
After #2157 cleanup

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2162]
#2157 introduced some code that needs cleanup.
1. Remove unnecessary macros. There is no explanation why we cannot use regular type parameters there and I cannot see one myself. Macros are much harder to maintain and debug than regular code. https://doc.rust-lang.org/std/hash/trait.Hash.html seems like a perfect fit and I don't see a reason why we need anything different. Notice how it allows us to have our own `Hasher`;
2. Remove unnecessary crate. There is no explanation why we need `typenum` crate there and I do not see one. We should keep the number of the dependencies to the minimum unless absolutely necessary;
3. The naming like `_hash_chain` is unclear. Why do we need to prefix it with underscore?

Assigning it to @SkidanovAlex and setting priority to P0 because big part of our infra uses crypto and I think it would create a significant technical debt if this code propagates through our codebase.

**Comment by abacabadabacaba** [comment]
1. We need macros because Rust doesn't have variadic methods. I'd rather write `hash!(a, b, c, d)` than `Hash::new().chain(a).chain(b).chain(c).chain(d).result()`.
2. We need `typenum` to implement `digest::FixedOutput` trait for `Hash256`.
3. The underscore is to signal that this is not a part of public API. These functions are used from macros, so they must be declared `pub`.

**Comment by nearmax** [comment]
1. Could you tell where in the code invocation like `hash!(a, b, c, d)` is used? At the end there is always some structure like `Block` that needs to be hashed the way it is used is by declaring `#[derive(Hash)]` on the structure which does this chaining;
2. We need `FixedOutput` just so that we can cast `Hash256` to `[u8; 32]` here: https://github.com/nearprotocol/nearcore/pull/2157/files#diff-b373a34a308cf983e4595833d5cb6c79R81 Why do we need to go through the trait? If we implement `Hash` trait on `Hash256` we can simply call `Hasher::write` on `[u8; 32]` instead of going through trait: https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html#tymethod.write
3. Got it, it is predicated on macros.

**Comment by abacabadabacaba** [comment]
1. Currently, `hash!` (and similar macros `hash_s!` and `prs!`) are used in `near_crypto::randomness` (11 uses) and `near_crypto::vrf` (4 uses). Among them, I found 4 uses with 4 arguments and 2 uses with 5 arguments.
2. We need `FixedOutput` to implement `Digest`. We use traits in `digest` crate instead of `core::hash` because this is what other crates we use do. For example, `blake2::Blake2b` implements `digest::Digest` but not `core::hash::Hasher`. If we switch to `core::hash`, we would need another wrapper type around `Blake2b` to implement the necessary traits.

**Comment by nearmax** [comment]
1. It looks like `hash!` uses one or two params, we do not need variadic power here.  If we implement Hasher trait for blake2 then we can do `(key, &self.0[..32 * k + 32])).hash(&mut blake2_hasher)` instead of `hash!(key, &self.0[..32 * k + 32])`.
2. Got it.

**Comment by abacabadabacaba** [comment]
Looking at `std::hash`, I see that it is not suitable for our use case:
* The `Hasher` trait assumes 64-bit output, which is too short for us.
* The documentation doesn't specify how exactly does `#[derive(Hash)]` would hash the structure. The result may depend on compiler versions, but we need consistent results.

In general, this module is designed for hashes used in hash tables, not for cryptographic hashes.

**Comment by nearmax** [comment]
>The documentation doesn't specify how exactly does #[derive(Hash)] would hash the structure. The result may depend on compiler versions, but we need consistent results.

Reading the documentation:

> The resulting hash will be the combination of the values from calling hash on each field.

I am sure it implies the order of declaration. 

In general, the arguments against Hash are convincing.
