### ISSUE TITLE
Adopt Feature Flags

### ISSUE THREAD

**Issue by damons** [nearprotocol/nearcore#2174]
To move to scheduled releases, developers must have the ability to quickly disable any code that is not ready to be promoted from `nightly` to the `beta` and `stable` branches.  

Let's begin.  

For more information on Feature Flags, this is a good read:  https://www.worthe-it.co.za/programming/2018/11/18/compile-time-feature-flags-in-rust.html

**Comment by damons** [comment]
This is a dependency for #2165

**Comment by ailisp** [comment]
We have a few compile-time feature flags, but mostly been used for expensive test or debugging. Should we name the flag to `nightly`, `beta` and `stable` so we could guard some features to nightly-only or beta-only

**Comment by damons** [comment]
Can we start with flagging any feature currently under active development that has yet to be merged to `staging` ?

In other words, let's begin gating all pull requests into `staging` related to new features or major changes that might result in a network failure--especially those?

We should have github issues for each of those.  Anyone currently working on code that's approaching a commit chime in and volunteer to start adding flags now, please?

**Comment by bowenwang1996** [comment]
I don't think we should use feature flags for features of our system, or at least not extensively. Feature flags are mostly for things like adversarial testing, expensive tests, etc.

**Comment by damons** [comment]
> Feature flags are mostly for things like adversarial testing, expensive tests, etc.

Is this true?  I'm not so sure.  

Also, if we can do this by using diffs and merges from feature branches (which is what we will be using as part of scheduled releases), we might not need them; however, I suspect they will be useful for adding well-defined/contained features we want to add in the future that put stability at risk.

**Comment by damons** [comment]
Adding Illia and Alex because I know they hecka influence nearcore's Rust code.

**Comment by vgrichina** [comment]
Ideally we need flags which can be enabled/disabled during execution time vs compilation time. So that eventually we can enable them on-chain.

**Comment by bowenwang1996** [comment]
Code will get very messy if we add a feature flag for every feature we add. It is already quite messy with the adversarial test flag.

**Comment by lazaridiscom** [comment]
> This is a dependency for #2165

I don't think that this issue blocks #2165.

**Comment by nearmax** [comment]
@damons We should be extremely careful, because it has the following disadvantages:
1. It makes the code less readable because it creates obscure dependencies. Suppose we have the following code:
```rust
  let v = get_some_vector();
  // lots of other code
```
and we decide to modify it to the following in nightly:
```rust
  let mut v = get_some_vector();  // Location A
  // lots of other code
  v.push(some_value);  // Location B
```
How should we decorate it with conditional compilation? Should it be:
```rust
 #[cfg(feature = "nightly")]
  let mut v = get_some_vector();  // Location A
 #[cfg(not(feature = "nightly"))]
  let v = get_some_vector();  // Location A
  // lots of other code
   #[cfg(feature = "nightly")]
  v.push(some_value);  // Location B
```
Or
```rust
 #[cfg(feature = "nightly")]
 {
  let mut v = get_some_vector();  // Location A
  // lots of other code
  v.push(some_value);  // Location B
}
 #[cfg(not(feature = "nightly"))]
 {
  let v = get_some_vector(); 
  // lots of other code
}
```
The second solution is definitely not preferable because it duplicates a lot of code, but the first solution makes it hard to read, e.g. someone reading code in location `A` will have no idea that it depends on location `B`. To make it more extreme, imagine location `A` and `B` be in different crates deep down in some functions.
2. Conditional compilation features can interfere. It is okay if someone uses `#[cfg(feature = "nightly")]` but what if they use `#[cfg(not(feature = "nightly"))]` or `#[cfg(all(feature = "latest", not(feature = "nightly")))]`. This will make the code very difficult to use
3. Conditional compilation features require threading in `Cargo.toml` files, e.g. if crate A depends on B and C then it needs to specify `nightly = ["B/nightly", "C/nightly", ..] ` and similar for other release features for all crates;
4. Some IDEs do not work well with features, e.g CLion.

2 and 3 can be fixed by having very strict guidelines about our codebase (which only became possible recently, because before our code was too volatile for delicate decoration like this one). 4 can probably be tolerated, especially since there is a chance we might be switching to VSCode eventually which would create a bunch of other painful issues anyway. 1 however looks to me like a large problem that we should have a solution for before we start decorating everything. @damons

**Comment by nearmax** [comment]
Few more questions:
* What is the process of promoting the code form `nightly` to `beta`? Are we going to replace-all `feature= "nigthly"` with `feature = "beta"` across our code base?
* It looks like we don't need `stable` feature, because the code that's not decorated with `nightly` or `beta` is the stable one, correct?

**Comment by damons** [comment]
What if we routinely surveyed our code for antiquated flagged code that we know is stable and removed the feature flags?  

Once something has been in our `beta` releases long enough, we can remove the adornments, maybe?

**Comment by damons** [comment]
> Few more questions:
> 
> * What is the process of promoting the code form `nightly` to `beta`? Are we going to replace-all `feature= "nigthly"` with `feature = "beta"` across our code base?
> * It looks like we don't need `stable` feature, because the code that's not decorated with `nightly` or `beta` is the stable one, correct?

I was actually thinking only enabled or disabled as possible choices.  I hadn't considered enabling by major branch.

**Comment by nearmax** [comment]
Also, this is relevant: https://github.com/nearprotocol/nearcore/issues/2115 If we decide to have conditional compilation flags for different modes of running the node then we need to have clean separation of these features from enabled/disabled, as noted by @bowenwang1996

**Comment by vgrichina** [comment]
@damons @nearmax  I think that it's far better to always compile same code, but have flags which are disabled/enabled in run time using config for now (and on-chain data at some point in future).

This will allow building and qualifying single Docker image and then enabling different features based on environment, etc. Will also more or less solve problem with code going stale.

**Comment by SkidanovAlex** [comment]
Specifically for compile-time flags, why is it better than branches in git?

If we do need to do something on the feature level (which is not very frequent, usually all the features from nightly get promoted to beta, and all the features from beta get promoted to stable), we can remove / add them selectively:

Disabling a feature = git revert.
Enabling a feature = git cherry-pick

**Comment by nearmax** [comment]
@SkidanovAlex For me `git cherry-pick` always results in a lot of pain especially for not well-encapsulated code.

**Comment by bowenwang1996** [comment]
@damons I am very against decorating code with feature flags for every feature that we implement. This will make code extremely unreadable, hard to maintain, and hard to review. Imagine you implement some feature that interferes with some other feature, you now need to modify some code blocks to add an additional feature and our codebase would be flooded with `[cfg(feature=blah)]`.

**Comment by nearmax** [comment]
> What if we routinely surveyed our code for antiquated flagged code that we know is stable and removed the feature flags?
> 
> Once something has been in our `beta` releases long enough, we can remove the adornments, maybe?

I suggest we survey on each release, instead of doing it periodically.

**Comment by vgrichina** [comment]
>  our codebase would be flooded with [cfg(feature=blah)]

@bowenwang1996 this is hard reality we will have to accept at some point. There also will need to be alternate code paths for different RPC protocol versions, etc. 

However given we will need flags at runtime going forward (for on-chain upgrades), I feel it's far better to start using runtime flags from beginning vs first moving to compile-time flags and then trying to figure out runtime flags later.
We should bake less config into binary, not more.

**Comment by lazaridiscom** [comment]
Elegantly modular and framework like architecture would make Feature-flags most possibly obsolete.

i guess.

**Comment by ilblackdragon** [comment]
@damons should we close this discussion at this point?

**Comment by damons** [comment]
So, conclusion here is that we should try to use them when we can.  Make sure it doesn't muddy code readability.  And, we're already doing it in some places. 

Closing this issue.
