### ISSUE TITLE
`tx-status` hangs for invalid hash

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#2195]
repro: `near tx-status 89gscCuj5qTv2YxsaXtAt9yYYEH6NXg2fjnytX2dghwT --account_id=ek-ethbridge-pusher`
near-shell version 0.20.1
target: testnet

Observed logs:
```
[WARNING] Didn't find config at /Users/ekwork/src/config, using default shell config
{
  networkId: 'default',
  nodeUrl: 'https://rpc.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.nearprotocol.com'
}
Error:  BadGatewayError:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

    at Object.fetchJson (/Users/ekwork/.config/yarn/global/node_modules/nearlib/lib/utils/web.js:44:36)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async JsonRpcProvider.sendJsonRpc (/Users/ekwork/.config/yarn/global/node_modules/nearlib/lib/providers/json-rpc-provider.js:53:26)
    at async /Users/ekwork/.config/yarn/global/node_modules/near-shell/commands/tx-status.js:33:24
    at async Object.handler (/Users/ekwork/.config/yarn/global/node_modules/near-shell/utils/exit-on-error.js:4:9) {
  message: '\n' +
    '<html><head>\n' +
    '<meta http-equiv="content-type" content="text/html;charset=utf-8">\n' +
    '<title>502 Server Error</title>\n' +
    '</head>\n' +
    '<body text=#000000 bgcolor=#ffffff>\n' +
    '<h1>Error: Server Error</h1>\n' +
    '<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n' +
    '<h2></h2>\n' +
    '</body></html>\n'
}
```

**Comment by bowenwang1996** [comment]
It is not easy to fix this. The main problem is that one cannot distinguish between the following:
* Transaction hasn't been included in any blocks yet.
* The transaction hash provided is invalid.
Since the block speed may vary from time to time, it is not clear how to fix this problem. Maybe we can have some expected block time and if the after that amount of time the transaction hash query still yields nothing then we consider the hash invalid, but that may still result in some false negatives.

**Comment by SkidanovAlex** [comment]
This affects `tests/stress/stress.py`, when this bug is fixed please fix the test as well.
I will tag places that I hacked to work around this issue with "2195".

**Comment by bowenwang1996** [comment]
@evgenykuzyakov @frol is it critical that we fix this before mainnet? If so, what would be a good solution?

**Comment by frol** [comment]
A timeout should be implemented as otherwise, it can easily lead to a deny of service.

**Comment by bowenwang1996** [comment]
@frol do you mean a smaller timeout? Currently it will time out.

**Comment by frol** [comment]
@bowenwang1996 it seems that the current timeout is higher than the timeout of the load balancer then.

**Comment by bowenwang1996** [comment]
Current timeout is 10s

**Comment by frol** [comment]
My experiment showed that querying a local node I get a timeout after 10 seconds with JSON-RPC reply, but querying testnet results in the same 10 seconds timeout with load balancer reply.

Do we really need to wait for 10 blocks (assuming 1s block production) before we timeout `tx-status`?

**Comment by bowenwang1996** [comment]
It is helpful when there is a network slowdown.

**Comment by frol** [comment]
Then it seems that there is no actionable item here.

**Comment by vgrichina** [comment]
1) Waiting for load balancer / nginx to fail with non-descriptive error is definitely undesired behavior. If it has to timeout – should better do it with nearcore response, not with `502 Bad Gateway`.
2) Given that nearcore seems to behave really badly when there are requests waiting for responses – I think maybe it's better to remove such waits on nearcore side and instead wait on client side when necessary? If nearcore haven't ever seen given transaction – I think it makes sense to return that it's not known vs waiting for it to be submitted later. Load balancer should use sticky sessions, so that if the same client submits transaction and then queries for it – given node should know about it.

**Comment by bowenwang1996** [comment]
I am not sure what the timeout is for nginx. It is possible that it is shorter than the nearcore timeout for rpc requests, which would result in people using 502 error instead of response from nearcore side.

I think the second suggestion is worth considering. Right now submitting transactions and tx status query use the same routine, which will wait for timeout. Maybe we should consider only keep it for transaction submission or remove waiting for both.

**Comment by ailisp** [comment]
Client side waiting sounds good to me. If people want to submit_txn_commit, near shell can keep trying get txn status and wait until it's committed/fail

**Comment by vgrichina** [comment]
is there anything besides `submit_txn_commit` and `tx-status` that is waiting for smth?

**Comment by frol** [comment]
Ideally, we should redirect the API client to the appropriate node tracking the right shard, but since the nodes do not expect to run RPC publicly, we cannot really do that.

Removing the internal awaiting will only increase the rps load, and don't solve anything in my opinion, so we should increase the timeout on the load balancer if we feel that 10s is a good timeout. People querying invalid transaction hashes should take care of their problems on their own.

**Comment by vgrichina** [comment]
> Ideally, we should redirect the API client to the appropriate node tracking the right shard, but since the nodes do not expect to run RPC publicly, we cannot really do that.

We can do it for nodes that we run ourselves.

> Removing the internal awaiting will only increase the rps load, and don't solve anything in my opinion

That is assuming that maintaining connection which polls internally doesn't cost anything. Not sure it's the case. Note that most clients likely will be naive and so if they are polling for `tx-status` you'll have multiple requests for the same hash all waiting. 

It would of course help a lot if we actually had some instrumentation to understand what is happening with RPC (how many requests processed, how many waiting for result, how long does event loop processing take, etc).

**Comment by frol** [comment]
> We can do it for nodes that we run ourselves.

All our nodes RPC are load balanced and thus, there is only a single entry point for an external observer. Thus, there is no sense in the redirect.

> That is assuming that maintaining connection which polls internally doesn't cost anything.

Well, external polling also has an overhead of HTTP communication. In general, I would expect that overhead higher than the internal waiting. We need to profile it and then we can make decisions. My completely unscientific benchmarks show pretty good performance on the devnet:

Setup:
* My Linux-based laptop (core i7-4710HQ)
* nearcore build from the latest master
* non-validator node connected to devnet
* single shard (started with no tracked shards and successfully switched to tracking shard #0)
* used `wrk` to load test the node running on the localhost

Results:
* `GET /` (it is here just for comparison, it is a non-existing endpoint which is served with static HTTP 405 response): 186'000 rps
* `GET /status` or `POST method=status` : ~36'000 rps
* `POST method=block` (non-existing block): ~92'000 rps
* `POST method=block` (existing block): ~24'000 rps (it is unclear why it is twice as slow as the chunks and transactions API)
* `POST method=chunk` (non-existing chunk): ~93'000 rps
* `POST method=chunk` (existing chunk): ~53'000 rps
* `POST method=tx` (non-existing transaction): ~66 rps (well, we have a 10 second timeout trying to resolve the transaction from the network, so load testing util just don't try to send more requests before receiving new responses, will need to try to just increase the concurrency)
* `POST method=tx` (existing transaction on the non-tracked shard): ~66 rps (!!! sixty six responses per second !!! and some of them timeout!)
* `POST method=tx` (existing transaction on the tracked shard): ~48'000 rps (muuuch better)

Benchmarking the APIs completely loads all my CPU cores.

I will need to focus specifically on the `tx` endpoint and put more tracing logs.

**Comment by vgrichina** [comment]
@frol I think pretty interesting benchmark would be to run request that polls and request that doesn't at the same time and see how they impact each other.

**Comment by frol** [comment]
I had increased the timeout on the load balancer, so instead of the HTTP Error 502 we get a proper JSON RPC Timeout Error.

As pointed in the comment above (https://github.com/nearprotocol/nearcore/issues/2195#issuecomment-592999965), there is currently no way to distinguish a hash of never existed transaction and a hash of a transaction that is still in the mem pool or dropped from the pool (#2039). Thus, there is no action item here, let's keep working on #2039.
