### ISSUE TITLE
Third Party Security Audit of Mainnet Genesis Contracts

### ISSUE THREAD

**Issue by nearmisterwhite** [nearprotocol/nearcore#2197]
Upd: I have added more contracts, since the review is going to be done for all of them together.

This includes the following contracts:
* Lockup/vesting contract;
* Staking pool;
* Voting contract;
* Whitelist contract;
* Fungible token contract;

Unfortunately the first two contracts are closely tied together, specifically we will allow staking from the vesting contract only through the staking pool. This is done to reduce the complexity of the contract.

**Comment by nearmax** [comment]
Assigning 5 days/points since this would be approximate amount of time spent fixing potential issues found by the security audit. @ilblackdragon @evgenykuzyakov I suggest we engage one of the security audit companies now so that we can start planning and have them work on in immediately once our contract is ready. Any objections?

**Comment by nearmax** [comment]
I have expanded the scope of this issue and changed the estimate from 5 to 21. @evgenykuzyakov please adjust it if you think it is not correct.

**Comment by nearmax** [comment]
The estimate was confirmed by a third-party audit company. They have started working on it Mon, May 11. It will take them about 3 weeks to finish it. Keeping the estimate to 21 to err on the safe side.

**Comment by nearmax** [comment]
This is done. Waiting for a report.
