### ISSUE TITLE
Expose seat price in validator RPC

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2259]
Currently there is no easy way to identify seat price that was selected for given epoch in `EpochManager`. Otherwise externally must rebuild auction and re-implement logic to compute seat price to recompute this.

We should expose it as extra field in `validator` RPC.

**Comment by frol** [comment]
@fckt Hey, can you take a look into it?

**Comment by bowenwang1996** [comment]
Given that logic isn't very difficult to implement (the seat price doesn't depend on the randomness beacon), why do we want to change code in nearcore?

**Comment by frol** [comment]
@ilblackdragon Do you have a link to the code where it is computed internally? (It helps a lot when there is a link to a relevant part of code)

**Comment by bowenwang1996** [comment]
@frol https://github.com/nearprotocol/nearcore/blob/175f42076fb383ffcfc565942e43e53183f09c01/chain/epoch_manager/src/proposals.rs#L9 It's like 20 lines of code and it's O(logN) so I don't think there would be performance issues

**Comment by frol** [comment]
@bowenwang1996 well, implementing this externally (e.g. on the near-api-js might be error-prone and may also get outdated, and then it would report incorrect values to the users), so I guess it makes sense to expose the value via RPC API. On the other hand, we want to expose just enough information from the node to avoid exploding our APIs with various needs. Thus, a separate service like Explorer backend indexer should be introduced, and since we consider having such a service, the information requested in this issue can be exposed via this "indexer" service reusing this exact source code.

**Comment by bowenwang1996** [comment]
That makes sense. I believe proposals are already exposed so there is enough information to recompute threshold.

**Comment by frol** [comment]
@ilblackdragon You have put it into mainnet milestone. Is it **required** for mainnet?

**Comment by ilblackdragon** [comment]
This data is needed somewhere.
For build this into explorer, we will not just need to process all tx, but also now rebuild full logic of EpochManager. It's not just `find_threshold` but a full logic of collecting proposals, evaluating them, collecting at the end of epoch which existing validators are kicked out and only then finding threshold. 
We probably should do that...at some point later. Seems awfully a lot of work, vs exposing one number via API.

**Comment by bowenwang1996** [comment]
Yeah it is more involved than I thought. I think we should expose this information, but also this makes me realize that calculating the threshold live is difficult -- we need to replicate the logic of epoch manager and cannot really be sure until the end of the epoch.

**Comment by fckt** [comment]
Since @frol asked me to take a look, I need to know the final decision to start working on it.
My opinion is: the node should have only necessary API. Everything additional should be implemented on the top.

**Comment by frol** [comment]
@fckt Well, the final decision is: we need this value exposed now since it is quite non-trivial to replicate outside. We may deprecate it in the future once we have the "indexer" service, but it is not even close.

**Comment by fckt** [comment]
should be it an extension of a `block` API?

**Comment by bowenwang1996** [comment]
@fckt I can take care of this change since I am very familiar with what needs to be done here.

**Comment by bowenwang1996** [comment]
@ilblackdragon I just realized that we can compute the threshold for a given epoch from the current validators (which is exposed in rpc) and the number of block producer seats (which we can easily expose without modifying anything in epoch manager). In fact, the threshold computed from the proposals for an epoch is the same as the threshold computed from the validators who are selected. To see this, let `T1` be the threshold computed from the set of proposals and `T2` be the threshold computed from the set of validators. It is obvious that `T2 >= T1` because `T1` is the threshold we use and therefore satisfies the inequality. On the other hand, if `T2 > T1`, since validators set is a subset of the proposal set, it means that `sum_{i} [P_i/T2] >= num seats`, contradicting the definition of `T1`. Therefore `T2 = T1`.

**Comment by ilblackdragon** [comment]
You are correct, it can be computed from the current set of validators. Thanks for pointing out!

And I guess any validator tooling will need to rebuild auction logic anyway to predict what will be next epoch's seat price for people who want to figure out how much to stake now.

I guess we don't need to modify nearcore then. Closing this and moving to explorer issue to add validator information in explorer.

**Comment by bowenwang1996** [comment]
I am happy to help with this on the tooling side and I think it will be important for validators. cc @frol

**Comment by frol** [comment]
@ilblackdragon I don’t see an issue on Explorer GitHub. Do we want to have it in near-api-js?

@bowenwang1996 It would be super helpful if you can write a pseudo code or a formula

**Comment by bowenwang1996** [comment]
@frol I can implement it in near-api-js. Although it is suboptimal to do this computation every time, especially in frontend. For explorer we should store the threshold in the backend, indexed by epoch id.

**Comment by frol** [comment]
@bowenwang1996 Let's have it in near-api-js first, and we will pick it up from there.
