### ISSUE TITLE
Upgrade the downcasting of `RuntimeError` in Wasmer

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2316]
Currently we are printing an error when we cannot downcast `RuntimeError` into the error type that we return through the host functions: https://github.com/nearprotocol/nearcore/blob/a08944db6672185618e2454fce5e7be0e327b47a/runtime/near-vm-runner/src/errors.rs#L78

The printed error also says that the output is non-deterministic.

As of `0.14.0` Wasmer returns ` ExceptionCode` there that we can try to downcast to. We should switch to this downcasting and also do not print that the output is non-deterministic anymore.

**Comment by fckt** [comment]
If we put Runtime errors into 2 categories:
1. Deterministic: the errors which are expected errors and we consider that the Node is healthy. 
2. Non-deterministic: such as node failure.

This is where we make a decision on the category:
https://github.com/nearprotocol/nearcore/blob/44bf10d5f618b50195e5ad122c0247aa30dee909/runtime/runtime/src/actions.rs#L190-L206

https://github.com/nearprotocol/nearcore/blob/a08944db6672185618e2454fce5e7be0e327b47a/runtime/near-vm-runner/src/errors.rs#L59-L90

Deterministic errors:
- VMError::FunctionCallError (all of them)
- VMError::InconsistentStateError

Non-deterministic:
- VMLogicError::ExternalError 

All deterministic errors are considered as a valid FunctionCall outputs. 

Is everything correct so far?

**Comment by fckt** [comment]
These tests are still returning "unknown" errors from Wasmer (`0.16.2`), but not `ExceptionCode`s:

https://github.com/nearprotocol/nearcore/blob/07f65c305f1575c27a3637bc59b37a8506363c3a/runtime/near-vm-runner/tests/test_error_cases.rs#L128-L139

https://github.com/nearprotocol/nearcore/blob/07f65c305f1575c27a3637bc59b37a8506363c3a/runtime/near-vm-runner/tests/test_rs_contract.rs#L155-L181

https://github.com/nearprotocol/nearcore/blob/07f65c305f1575c27a3637bc59b37a8506363c3a/runtime/near-vm-runner/tests/test_error_cases.rs#L154-L165

ref
https://github.com/wasmerio/wasmer/issues/1338

**Comment by nearmax** [comment]
FYI @olonho We have a lot of complexity around error handling in Wasm that you should be aware of.

**Comment by nearmax** [comment]
Added more context here: https://github.com/wasmerio/wasmer/issues/1338.

For now let's keep unknown error, since we don't have sharding and slashing it will not cause slashing. I asked Wasmer to prioritize it. Closing this issue since we https://github.com/nearprotocol/nearcore/issues/2055

**Comment by bowenwang1996** [comment]
But even with a single shard, why couldn't this cause state to diverge?

**Comment by fckt** [comment]
Great question! I guess, the logic is the following: imagine, there is no guarantee that (due to internal errors) node producer is not following the protocol (it could be an internal error). It means that it will produce non-valid block. The assumption that the non-valid blocks will be ignored by the subsequent block producers (validators). 

But I don't know the specific details of how block producers behave in this case, so this question is open for me too.

**Comment by bowenwang1996** [comment]
@fckt what you said is true, but it may cause the network to diverge when more than 1/3 block producers have the same post state root while the rest has another. It can cause the network to stall for quite a while if that happens.

**Comment by fckt** [comment]
Right now we can't do anything. Wasm spec defined as deterministic (with exceptions we eliminated). The problem is that we can't separate Internal Wasmer (and internal host) errors from Wasm traps and Host logic errors today.. 

This issue only about updating Wasmer and we hoped it will solve the problem. But it's not, due to bug in Wasmer - it doesn't return ExceprionCode's in the relevant cases (https://github.com/nearprotocol/nearcore/issues/2316#issuecomment-608497650).
