### ISSUE TITLE
Protocol version change

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2373]
There has been some discussion around how we should update protocol version to align with the release process. There are two approaches:

1. Every change that changes the protocol, when merged into master, increase `PROTOCOL_VERSION` in master by 1.
2. Every change that changes the protocol, when merged into master, increase the `PROTOCOL_VERSION` in master if the protocol version in master is the same as the protocol version in stable. Otherwise the protocol version remains the same. This way we only increment protocol version by at most 1 between a full release cycle (from master to stable).

Pros and cons of the first approach (which is what we use now):
pros: 
* Easy to follow. There is no need to check the protocol version in another branch.
* If a developer implements the change from version X to X+1, they only need to write the migration script (if necessary) for their own change without having to interact with the other migration scripts.
cons:
* Since we will use protocol version as part of the binary semver, between two releases there might be a version jump. For example, the release after 1.4.1 can be 1.12.0.
* When there are multiple PRs that change the protocol version that the same time, it can be annoying to resolve conflicts.

In my opinion, it is important that we do not have huge version jumps, e.g., from 1.4.1 to 1.12.0, so I would like to consider the second approach, or figure out a better way to handle versions.

**Comment by ailisp** [comment]
I think the second cons of first approach is even worse in second approach. Consider PR#1 change protocol_version 4 to 5, PR#2 change some other protocol but with first approach it will still use protocol_version 5. We did a beta release at sometime includes PR#1 but not yet PR#2, it's hard to automate another release of PR#2 since by definition it's 5=>5 we doesn't run any migration.

About first cons,
> Since we will use protocol version as part of the binary semver, between two releases there might be a version jump. For example, the release after 1.4.1 can be 1.12.0.

This is a problem. But if you think this way: betanet is increasing protocol_version, most likely 0-2 times since it release weekly. stable testnet can increase a lot because it's release less often, but it's actually good that it matches betanet's protocol version. To answer people why protocol version increase a lot: because stable is just some stabled beta, beta is increasing gradually and to now stable is increased a lot.
Or, I think we can use date as protocol_version, so people cannot see it's a small jump or huge jump :D

**Comment by ailisp** [comment]
In long term we're also expecting fewer and fewer changes in protocol version, so between two stable release there's possible no or few version jump

**Comment by bowenwang1996** [comment]
> I think the second cons of first approach is even worse in second approach. Consider PR#1 change protocol_version 4 to 5, PR#2 change some other protocol but with first approach it will still use protocol_version 5. We did a beta release at sometime includes PR#1 but not yet PR#2, it's hard to automate another release of PR#2 since by definition it's 5=>5 we doesn't run any migration.

Good point. I didn't think of this before.

**Comment by bowenwang1996** [comment]
It seems that we have agreed to use the first approach and that skipping some versions is fine. Closing the issue.

**Comment by ilblackdragon** [comment]
I would disconnect `PROTOCOL_VERSION` from binary versions. 
`PROTOCOL_VERSION` really is for internal use to measure migrations and related stuff.

We actually going to have backward compatible binaries with different PROTOCOL_VERSION going forward.

For example we updated storage format but kept it backward compatible - when binary loads and detects that storage is of old `PROTOCOL_VERSION` it upgrades storage internally.
E.g. when we are going to implement https://commonwealth.im/near/proposal/discussion/261-upgradability?comment=649
