### ISSUE TITLE
Potentially dangerous implementation of parse_account_id_from_access_key_key

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2408]
Current implementation of `parse_account_id_from_access_key_key` is dangerous, but not incorrect, it just relies too much on the engineers to use it correctly. https://github.com/nearprotocol/nearcore/blob/77ddd8f2174ad9167e5dc816b34fe2a4249a8a6d/core/primitives/src/trie_key.rs#L265 as commented here https://github.com/nearprotocol/nearcore/pull/2253/files/8a701155907a4a5ccddc45f950eebacecf62b245#r392026033 we assumed that this would be auto-fixed if we hashed account ids, but we are postponing it see https://github.com/nearprotocol/nearcore/issues/2215#issuecomment-610105016 

The reason why it is correct is because account id never contains 0x02 and we always use 0x02 as a separator between the account id and the public key. The first 0x02 that we encounter while searching <account_id>0x02<public_key> from the left is the actually valid separator. We however need to make sure we read raw access key only using `parse_public_key_from_access_key_key` and `parse_account_id_from_access_key_key`. Ideally we should encapsulate access key with account id in a Rust structure that implements this deserialization in one place.

**Comment by nearmax** [comment]
CC @evgenykuzyakov @frol

**Comment by frol** [comment]
Oh well, after another look I realized that I missed the fact that there is indeed a separator `col::ACCESS_KEY`, so the storage key is, essentially, constructed as `col::ACCESS_KEY + account_id + col::ACCESS_KEY + serialized_public_key`! I missed the fact that it is a constant there, which can be used instead of the magical `2`! I will submit a PR to fix my crap.
