### ISSUE TITLE
Nightly failure: sanity/transactions.py

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2550]
Fails occasionally. Example runs:

http://nightly.neartest.com/run/2cef4105736ab969470df2751e78fd3f0fc0a81d_200428_102644
http://nightly.neartest.com/run/2cef4105736ab969470df2751e78fd3f0fc0a81d_200428_072213

Failure:

```
Traceback (most recent call last):
  File "tests/sanity/transactions.py", line 66, in <module>
    assert False, "Balances before: %s\nExpected balances: %s\nCurrent balances: %s\nSent at height: %s, cur height: %s\n" % (last_balances, ctx.expected_balances, ctx.get_balances(), sent_height, height)
AssertionError: Balances before: [1000000000000000000000000000000241, 1000000000000000000000000000001066, 999999999999999999999999999998829, 999999999999999999999999999999864]
Expected balances: [1000000000000000000000000000000974, 1000000000000000000000000000000619, 999999999999999999999999999998712, 999999999999999999999999999999695]
Current balances: [1000000000000000000000000000000974, 1000000000000000000000000000000619, 999999999999999999999999999998712, 999999999999999999999999999999695]
Sent at height: 59, cur height: 72

```

Sent at height is very often == 9 (mod 10), though in at least one run it was == 0 (mod 10)

**Comment by mikhailOK** [comment]
http://nightly.neartest.com/run/2cef4105736ab969470df2751e78fd3f0fc0a81d_200428_072213

- there is a tx for shard 0 sent at height `59`. The test sends transactions to `test0`.
- Epochs: `42..51`, `52..61`, `62..71`, `72+`
- for heights `42..71` shard 0 chunks are produced by `test2`
- for heights `72+` shard 0 chunks are produced by `test0`, and tx correctly gets included at height `72`

The test fails when `test0` receives the transaction at height `62`, and decides not to forward it.

The bug was introduced in #2524: it broke the contract between `process_tx_internal` and `active_validator`.
For `process_tx_internal`, the node doesn't forward the tx if it's an active validator:
```
                let active_validator = self.active_validator(shard_id)?;
....
                if active_validator {
                    // Don't forward to next epoch validators if we've already seen the tx.
                    // This is to prevent forwarding loops.
                    if new_transaction && !is_forwarded {
                        self.possibly_forward_tx_to_next_epoch(tx)?;
                    }
                    Ok(NetworkClientResponses::ValidTx)
                }
```

#2524 broke `active_validator` by making it return true if the node is a validator in next epoch:
```
            if &chunk_producer == account_id || &next_epoch_chunk_producer == account_id {
                return Ok(true);
            }
```

**Comment by mikhailOK** [comment]
@bowenwang1996

**Comment by mikhailOK** [comment]
Sounds like the fix is to also check that epoch switch is possible
```
            if &chunk_producer == account_id || (&next_epoch_chunk_producer == account_id && next_epoch_is_possible(head.height + i)) {
                return Ok(true);
            }
```

**Comment by bowenwang1996** [comment]
@mikhailOK yes I forgot to add the check that epoch switch is possible

**Comment by mikhailOK** [comment]
@bowenwang1996 actually why is the change to active_validator needed at all? `test_tx_forward_around_epoch_boundary` passes without it.

**Comment by SkidanovAlex** [comment]
Reopening, fails again with the same symptoms:

http://nightly.neartest.com/run/17943ad2d6eb79dd23600288fde01baeaf909c97_200430_045529

**Comment by mikhailOK** [comment]
`test2` has suspicious errors in the log #2585, but that shouldn't break the test. Something else is wrong

**Comment by mikhailOK** [comment]
- for epoch `13.22` `test0` validates shard `0`. it will also validate for `33..42`
- After producing chunk for `22` but before producing block `22` `test0` receives transactions for shard `0` and hodls them.
- It reaches this code:
```
                let active_validator = self.active_validator(shard_id)?;

                // If I'm not an active validator I should forward tx to next validators.
                debug!(
                    target: "client",
                    "Recording a transaction. I'm {:?}, {} is_forwarded: {}",
                    me,
                    shard_id,
                    is_forwarded
                );
                self.shards_mgr.insert_transaction(shard_id, tx.clone());

                // Active validator:
                //   possibly forward to next epoch validators
                // Not active validator:
                //   forward to current epoch validators,
                //   possibly forward to next epoch validators
                if active_validator {
                    if !is_forwarded {
                        self.possibly_forward_tx_to_next_epoch(tx)?;
                    }
                    Ok(NetworkClientResponses::ValidTx)
                } else if !is_forwarded {
                    self.forward_tx(&epoch_id, tx)?;
                    Ok(NetworkClientResponses::RequestRouted)
                } else {
                    Ok(NetworkClientResponses::NoResponse)
                }
```

`active_validator` has a bug at last block in the epoch, what's weird is that `head` is supposed to be at height `21` so that bug shouldn't matter in this case.

**Comment by mikhailOK** [comment]
Unclear what exactly happened in that nightly run, but #2586 and #2587 might have fixed it.
