### ISSUE TITLE
GC doesn't work when there is more than one shard

### ISSUE THREAD

**Issue by mikhailOK** [nearprotocol/nearcore#2564]
Similar to #2563, there is one set of TrieChanges per block per shard, but the GC code uses `block_hash` as key, effectively storing changes for one arbitrary shard for each block:
```
store_update.set_ser(ColTrieChanges, self.block_hash.as_ref(), &self.trie_changes)?;
```

We should be mapping from `chunk_hash` or `(block_hash, shard_id)`.

**Comment by mikhailOK** [comment]
In theory this should be causing garbage leaks rather than deleting too much (#2500 #2544 #2556), so there must be more bugs

**Comment by Kouprin** [comment]
`TrieChanges` are not connected to exact shard. I suppose there is the only Trie for all shards, and there is no separation between different shards in Trie.
Before we can update `TrieChanges` to be stored for different shards, we must connect `TrieChanges` with shards explicitly. More precisely, we need to handle as many Tries as many shards we have. Otherwise, we're unable to identify which TrieChanges are related to which shard and part of the Trie.

**Comment by damons** [comment]
Setting estimate to 1 because this is mostly done and waiting for Misha's fix.

**Comment by bowenwang1996** [comment]
@damons This is not even blocking phase 2, not sure why we need an estimate now.
