### ISSUE TITLE
Voting contract. Tests

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2663]
Following discussion during the middleware sync assigning this item to @bowenwang1996 and setting the estimate to 5 days.
CC @evgenykuzyakov

**Comment by bowenwang1996** [comment]
@evgenykuzyakov is this done?

**Comment by evgenykuzyakov** [comment]
Unit tests are done by @bowenwang1996 , but it's not tested with real nodes

**Comment by evgenykuzyakov** [comment]
I can't claim this as done, since I've just fixed an issue by just reading the code. But:
- The code is simple and I have proof read it.
- Unit tests are covering most of the paths.
- There is a script to test it on localnet (that didn't cover the kick out bug)
- We've been testing it on testnet with validators and would have discovered the issue.

I'm 95% confident in the implementation contract and testing.
To get to the 100% we need betanet testing.

Note that it doesn't cover lockup integrated testing

**Comment by evgenykuzyakov** [comment]
I'm going close, since I'm confident with unit tests + localnet simulation to cover most of the issues. Covered by  https://github.com/near/core-contracts/pull/81
