### ISSUE TITLE
Update release schedule

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2670]
Original discussion: https://near-community.slack.com/archives/C0132RCT6AC/p1589190011058000

Some discussion:
 * Currently we release betanet weekly and stable every 4 weeks
 * This is for sure too long for releases into stable, it should be weekly as well with lag from beta release.
 * For critical bug fixes - we should have out-of-schedule releases (see Cosmos - https://github.com/cosmos/cosmos-sdk/releases)
 * Given we should stop changing protocol at this point, we can have releases more often without protocol changes, so validators can update at will but we can start testing new code early.
 * Protocol changes should be backward compatible (https://github.com/nearprotocol/NEPs/pull/64). BetaNet can be running the bleeding edge of protocol while TestNet can only update to next protocol in specific times (e.g. once a month as we were planning).
 * We can run "canary" of new release (beta) on TestNet right away with 1 validator and 1 RPC node making sure it works with old protocol and that everything works correctly. 
 * Compared to BetaNet network runs new protocol directly.

**Comment by bowenwang1996** [comment]
Meta concern before we discuss the details: I don't think the issue should be in this repository. We have long been hijacking the release of the protocol with nearcore releases and while that is fine at the moment, we should stop doing it for the purpose of disentangling the client specific releases from the protocol-level releases. Therefore I suggest we move this issue to https://github.com/nearprotocol/NEPs

**Comment by ilblackdragon** [comment]
This is not protocol release schedule but this client's release schedule.
Protocol updates should indeed be discussed in NEPs.

**Comment by chefsale** [comment]
One proposal I was thinking about is a biweekly release cycle:

**For minor releases and patches:**
- Alpha - latest master build running on devnet daily 
- Beta - 2 weekly builds running on betanet
   - everything goes into master linearly, except critical security patches and bug fixes

- Release Candidate 
   - 2 weeks of stabilization on testnet
   - we only cherry-pick critical security patches and bug fixes included in previous releasesinto the rc branch
   - we revert newly introduced bugs from the last release instead of forward fixing new issues

- Stable - we create a stable release and repeat

**For major releases I would use the same concept, but with a longer stabilization period maybe, but  we can adapt the cadence later on, but this would be a healthy start I believe for now.**

As well I propose creating a diary for releases previous and future major ones.

Let me know what you think of this process? cc: @damons @ilblackdragon @bowenwang1996  @ailisp as well free to tag other relevant people, so I don't spam everybody.

**Comment by bowenwang1996** [comment]
@chefsale Looks good except that I think there is no need for alpha. Otherwise we pretty much have one new version every day, which I think is a bit excessive.

**Comment by ailisp** [comment]
near-nightly-2020-05-22 :)

**Comment by chefsale** [comment]
As @ailisp said we currently have nightly aka we can just call it alpha and have it for internal use only. We wouldn't create a release for these on the github release page but just have the builds stored in s3 like we do now, it would be just easier to reason about promotion and we already have all the releases stored and ready if that makes sense. As well for development reasons if needed.

**Comment by bowenwang1996** [comment]
@chefsale that sounds good to me.

**Comment by ailisp** [comment]
Sounds good to me. It's great to have all master binary for development
binary. It's also valuable to use for quickly test/deploy betanet/testnet
with a given commit

**Comment by bowenwang1996** [comment]
> we only cherry-pick critical security patches and bug fixes included in previous releasesinto the rc branch

Do you suggest having a separate branch for release candidates? @chefsale
