### ISSUE TITLE
Implement a PeerPool

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2754]
Implement a new struct PeerPool.
It gets initialized with Max peers.
Creates this many threads via Artbiters and Peer Actors in them. PeerPool would maintain which actor slots are "available".
When PeerManager right now spun up new actor, it will instead find available peer In the pool and send message to it with needed arguments.
Peer actor should change to initialize with empty and receive arguments via message.
Instead of killing actor, record in PeerPool that actor is available again.

Reasoning: we want to have peer peer per thread. Sync Arbiter doesn't match use case as Peer actor are stateful.

**Comment by bowenwang1996** [comment]
I feel like creating 40 threads might be too much overhead. What if we create subpools and group say every five peers into a subpool and each subpool is controlled by one arbiter? If one peer is attacking it can only stall one subpool, which shouldn't affect the node too much.

**Comment by mfornet** [comment]
@bowenwang1996 I agree that one thread per Peer (active connection) might be too many. What I will do instead is try to create a pool of threads (let's say ~5-10 threads) and start all PeerActor inside that pool. 

This way resources will be distributed better than if we assign one thread every 5 peers, since it is possible in the latter approach that 2 peers are competing for the same thread while other 5 peers in separate subpool are almost idle.

The only drawback is that I don't know how to do this within actix, will investigate.

**Comment by mfornet** [comment]
After researching on this topic, found that creating a threadpool for Actors is more complex than expected, since it is not supported by default, and actors heavily depends on Arbiters. Doing this will require very low level and careful management of message within actors, which will take more time than required. 

I propose for now we have one thread per PeerActor and let the operating system manage them (we will have at most 40 threads dedicated for this). In general PeerActor is not very expensive to run. We should only handle appropriately abusive peers so that they can't hijack the node CPU.

What I don't like about allocating peers in subpools, is that it is possible that some thread becomes idle at some point (if all peers in that thread becomes idle), while peers within some other thread will be competing.

**Comment by mfornet** [comment]
After researching on this topic, found that creating a threadpool for Actors is more complex than expected, since it is not supported by default, and actors heavily depends on Arbiters. Doing this will require very low level and careful management of message within actors, which will take more time than required.

Notice that [actix-threadpool](https://github.com/actix/actix-net/tree/master/actix-threadpool) exists, but is basically a threadpool used for blocking operations, it doesn't handle actors.

I propose for now we have one thread per PeerActor and let the operating system manage them (we will have at most 40 threads dedicated for this). In general PeerActor is not very expensive to run. We should only handle appropriately abusive peers so that they can't hijack the node CPU.

What I don't like about allocating peers in subpools, is that it is possible that some thread becomes idle at some point (if all peers in that thread becomes idle), while peers within some other thread will be competing.
