### ISSUE TITLE
Discussion: should tests failing due to known reasons be enabled in nightly

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2758]
We have several tests today (e.g. #2208) that are failing in nightly.

Want to start a short discussion on whether such tests should be enabled in nightly or disabled.

Main reason to disable that I see: when people push changes, they need to check nightly to see if their change breaks anything. If there are known failing tests, it's harder to see whether there was a regression.

Main reason to enable is that if we have tests intentionally left out, we can't (at least easily) have an automatic script that checks that all the tests are included.

Thoughts?
@bowenwang1996 @ailisp @chefsale

**Comment by SkidanovAlex** [comment]
Actually, in that particular case I guess we can just add `#[ignore]` in front of the test.
What would be an easy way to mark python tests as known to fail?

**Comment by ailisp** [comment]
> Actually, in that particular case I guess we can just add #[ignore] in front of the test.
What would be an easy way to mark python tests as known to fail?

There's two different use of ignored tests:
1) ignore and don't even run the test
2) run test, but if it's failed, marked it as "IGNORED FAIL" / "ALLOWED FAIL" instead of "FAIL" (and we only check "FAIL"/"TIMEOUT" as criterion of fails

`#[ignore]` does 1) but I think 2) would be more helpful, and it's not obvious to ignore pytest with 1) anyway. Going forward with 2) we can add "allow_fail" in nightly.txt and modify nightly runner to  handle it

**Comment by bowenwang1996** [comment]
Yeah I think we can "allow" some pytests to fail so that we can both see the test is being run and also whether tests that are supposed to pass have regressed.

**Comment by SkidanovAlex** [comment]
> we can add "allow_fail" in nightly.txt and modify nightly runner to handle it

I like this idea a lot.
