### ISSUE TITLE
RPC response time is ridiculously long

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2984]
Some actix web logs from our rpc node
```
Jul 11 08:50:14.518  INFO actix_web::middleware::logger: 34.94.78.219:56734 "GET /metrics HTTP/1.1" 200 18702 "-" "Prometheus/2.18.1" 0.000696
Jul 11 08:50:15.424  INFO actix_web::middleware::logger: 45.14.224.113 "POST / HTTP/1.0" 200 43695 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 8.896882
Jul 11 08:50:15.427  INFO actix_web::middleware::logger: 35.203.153.166 "POST / HTTP/1.0" 200 9552 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 7.269010
Jul 11 08:50:15.426  INFO actix_web::middleware::logger: 35.203.153.166 "POST / HTTP/1.0" 200 9552 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 8.324753
Jul 11 08:50:15.428  INFO actix_web::middleware::logger: 14.52.147.51 "POST / HTTP/1.0" 200 305 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 6.739616
```
The format of the log can be found here https://docs.rs/actix-web/2.0.0/actix_web/middleware/struct.Logger.html. Notice that the last number is the response time in seconds, meaning that while some requests take < 1ms to serve, some take  more than 8 seconds to serve, which doesn't feel right.

**Comment by frol** [comment]
I believe that is the recent issue that caused betanet downtime when a flood of view method calls would block near-client and/or near-view-client leading nodes to fall out of sync. It is a long-standing issue once discussed in #2313. I hope #2970 will at least partially address this. Otherwise, the only fix I see is getting back to rate-limiting specifically view method calls as they are really abusive.

To DoS the node to a crawl you just run a single line:

```
ab -T 'application/json' -c 1000 -n 10000 -p view-call.json http://127.0.0.1:3030/
```

where `view-call.json` file is, e.g.: `{"method":"query","params":["account/masternode24",""],"id":123,"jsonrpc":"2.0"}`

**Comment by ilblackdragon** [comment]
Given #2970 is merged - has this resolved the issue?
Also we should consider adding guards for some of the RPC methods given some are way more expensive than others. 
We can guard it either via configuration or HTTP authentication.

**Comment by bowenwang1996** [comment]
It's not available on any live network. Maybe we can use mocknet to check for rpc response time.

**Comment by bowenwang1996** [comment]
close in favor of #3270
