### ISSUE TITLE
investigate database migration failure

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#3247]
During a migration from database version 6 to version 7 (which changes transaction and receipt refcounting), many nodes on betanet failed with number of transactions in `ColTransaction` not matching the number of refcounts in `ColTransactionRefCount`, which indicates an inconsistency in the storage. We should investigate such failure and prevent it from happening again.

**Comment by mikhailOK** [comment]
Possible way it could happen: `decode_and_persist_encoded_chunk` in version 6 increments refcounts, but does not save transactions.
If that's the case, 
- store validator should fail in validate::chunk_tx_exists
- there is a chunk with transactions not in storage
- there is no block with this chunk
Going to verify it from the repro dump

**Comment by mikhailOK** [comment]
- There are two transactions in ColTransactionRefCount that are not in ColTransactions
- Both these transactions are in one chunk with `height_created and height_included: 11603776`
- **There is a block in storage with this chunk included**
- Chain head is at height `12388051`

store-validator actually has the check disabled because it's a known bug: #2930
Investigating why this happens

**Comment by mikhailOK** [comment]
pre-migration storage writes to `ColTransactions` only in `apply_chunks`, and only when `care_about_shard && chunk_header.height_included == block.header().height()`.
Writing to `ColTransactionRefCount` happens for all chunks saved by `save_chunk`, so seems like `save_chunk` could happen without `apply_chunks called && conditions met`.

In the dump the node has no blocks between `11592636` and `11603776`, and the parent of `11603776` has height `11603775`, so it was likely the `save_chunk` called from `set_state_finalize` on state sync.

Plan for fixing:
- Re-enable the store-validator check. The `ColTransactions` inconsistency should be fixed as a side effect of storage version 7
- Try to get rid of `save_transactions`. Now it's only used by `get_transaction` on `ChainStoreUpdate`, and it's bug-prone because it's inconsistent with when transactions are written.
- Update migration code to repair storage instead of asserting
- **Important**: the bug also affects `ColReceiptIdToShardId`, and it's still there. Insertion happens in `apply_chunks` with conditions, but deletion happens for any saved chunk. So we need a fix and a migration step that repairs this case.
- Investigate other things we save in tomfoolery `apply_chunks`.

**Comment by bowenwang1996** [comment]
@mikhailOK thanks for investigating this. Notice that we don't necessarily apply every chunk we save. If, for example, there is some shard we don't care about and we receive enough chunk parts for some chunk in that shard, we will still decode and save the chunk.
