### ISSUE TITLE
Block producer doesn't populate authority_mask

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#377]

**Comment by nearmax** [comment]
The fix makes authority mask to always have one non-false element corresponding to the producer of the block instead of having it assigned to all those who signed it. 

It seems the problem is that we have not clarified the mechanism of signing the blocks thoroughly enough. If we want the authorities to be able to rollover their stakes then they need to agree on exactly the same set of peers who signed the block, because otherwise the authority schedules that they compute will be different. This agreement on who exactly signed the block is not currently guaranteed by TxFlow, specifically one peer might see 2/3+ finalization endorsements and another peer might see another set of 2/3+ finalization endorsements.

Therefore I suggest we disable rollover for now. Which means that an authority that wants to continue participating should explicitly re-send their staking transaction. That will also remove some of the moving parts for now. Once our TestNet is working well we can add this convenience-feature. This might require having a fully-working beacon chain consensus.
WDYT? @ilblackdragon @SkidanovAlex 

I am reopening this issue and assigning to myself.

**Comment by ilblackdragon** [comment]
The fix has one authority, because currently we are only have one authority per block.
If we don't have clarified process of signing & agreement on the set of authorities (which is the requirement for Beacon Consensus) - we should do that ASAP (e.g. tomorrow morning). My understanding was that @SkidanovAlex has it figured out.

Without roll over we going to stall our test network super fast. So I would strongly urge not to disable rollover.

If you want to test things without TxFlow, just set the number of seats to 1 seat per block.

**Comment by nearmax** [comment]
As long as we have our own nodes participating in the TestNet it should not stall, because our nodes will participate non-stop and will stake themselves constantly. We can even make it an opt-out command line arg.

If we decide to keep the roll over then I would prefer if we hack the fast simple Beacon Consensus: 
> Run the current version of TxFlow for 10-20 blocks and take the signers of the first block as participants. By the block 10-20 everyone would know for sure who are the participants of the first block.
It will allow us to start adding integration tests and benchmarks for the entire TestNet, which will allow us to move faster because we will have a safe-net that catches all bugs. It is much easier working with a code that you can run end-to-end than the code that only has sporadic unit tests.

Otherwise, assuming we have a solid design of Beacon Consensus it will take time to implement it and would require having a person working on it.

**Comment by david-stolp** [comment]
I removed a "TODO" comment in #475 that refers to this issue.  The authority_mask has moved into the GroupSignature, where it indicates who signed the block.

**Comment by ilblackdragon** [comment]
Done.
