### ISSUE TITLE
Add signature verification in node/runtime

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#424]
Currently we only verify TX signatures at rpc level. We probably should do this at runtime.
the good place for this is in "fn apply_signed_transaction(" in node/runtime/src/lib.rs after we fetched sender's account and have both signed transaction and public keys.
It requires fixing tests since tests use default signatures.
@azban Why do you need caching?

**Comment by azban** [comment]
we don't need it immediately. caching is just an optimization so that we don't go have to check a signature more than once.. because we will be checking it at least 3 times per transaction on a single node. the major thing is reducing db lookups for public keys. we may want to do this at a lower level, especially because runtime is going to be requesting it anyway.
