### ISSUE TITLE
check block index does not already exist when adding blocks

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#428]
this made this test really unfun https://github.com/nearprotocol/nearcore/blob/fb8bfb05ea36c0f29aae9bf780c69edc0d96312d/core/shard/src/lib.rs#L194 .. and seems like this should not be acceptable behavior.

**Comment by azban** [comment]
cc: @nearmax @ilblackdragon

**Comment by nearmax** [comment]
This check should be done inside the beacon/shard chain and it should more than just a filter based on block index, instead it should take into account forks and what block index is on each fork. Since there is an algorithm behind the fork choice rule it is safer if we always attempt importing the block into the chain but the chain should reply whether it has accepted the block, whether it has changed the current block (as either a result of progressing through blocks on the same fork or switching forks). This is a part of a larger discussion on what is a state of the chain, how it changes, and who should be aware of it. I will try to produce some coherent plan on what to do with those states tomorrow.

**Comment by evgenykuzyakov** [comment]
@nearmax Is it still relevant?

**Comment by nearmax** [comment]
Nope. We are not taking into account different geneses.

**Comment by ilblackdragon** [comment]
Done.
