### ISSUE TITLE
Mempool is racy

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#638]
I am looking at the mempool code and it is quite racy.
For instance here: https://github.com/nearprotocol/nearcore/blob/master/core/mempool/src/lib.rs#L44
You can see how we locking twice in `add_transaction`. During the first unlock we create state update object, during the second one we add it to the transactions list. If in between these lines the blockchain progresses to a new block (with a new state) then I do not know what will happen after we apply the outdated transaction state.

**Comment by bowenwang1996** [comment]
The problem is not easy to fix. StateViewer has a read lock on storage when viewing the state, and we have to hold the write lock to access the root before creating the `TrieUpdate` object.

**Comment by ilblackdragon** [comment]
There is no problem with state update @nearmax per se. Invalid tx will just be invalid tx.
Instead, we actually must re-validate transactions on block importing (right now we just remove ones that are added) because it's possible that some transactions became invalid due to lack of funds or nonce increase. 
In `add_transaction` / `add_receipt` we should take a lock on `transactions`/`receipts` HashSet and the same in `import_block` to prevent race conditions between those two functions. 

@bowenwang1996 you want to add this logic?

**Comment by bowenwang1996** [comment]
I don't see the race condition between `add_transaction` and `import_block`.

**Comment by ilblackdragon** [comment]
add_transaction should lock `self.transactions` before
```        if let Ok(Some(_)) = self
            .storage
            .write()
            .expect(POISONED_LOCK_ERR)
            .transaction_address(&transaction.get_hash())
        {
            return Ok(());
        }
```
otherwise, right now it can check that TX is not in the block, and then block import happens (and it's in the block) and then we add tx to transaction pool (and we don't check again, which we shouldn't).
E.g. just grab a guard on `self.transaction` in the beginning of the function.

**Comment by nearmax** [comment]
I would recommend to simply have a lock on the entire pool and avoid having internal locks until we solidify our infra and start doing optimizations like fine-grained locking. Using guard to lock the code has several cons:
* It makes code more obscure because the moment of unlocking is implied by the scope, which might not be the same scope as the moment of locking. E.g.
```
{
 let mut guard;
  {
    guard = obj.write().expect(..);
    <do something>
  }
  <do something else>
}  // unlocking happens.
```
* Guard are useful but locking the code oppose to locking the data is discouraged in Rust, and APIs make it hard to do on purpose. "Lock data not code".

**Comment by bowenwang1996** [comment]
I agree with what Max said. @ilblackdragon What do you think?
