### ISSUE TITLE
Rotate preference for Nightshade

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#655]
Currently, it always ends up preferring block proposal from the same authority. We should rotate who's block is preferred.

**Comment by mfornet** [comment]
One easy fix for this now is using block hash as tie breaker instead of authority id. The problem with this is that nodes can try to produce blocks with higher hashes (Adding fake transactions). So we need a way to effectively rotate participants random, using information from beacon chain which can't be manipulated.

**Comment by mfornet** [comment]
I replaced order to prioritize hashes in #656.

**Comment by mfornet** [comment]
I'll close this issue in favor of #657
