### ISSUE TITLE
Nightshade stalls if the highest id goes offline

### ISSUE THREAD

**Issue by mikhailOK** [nearprotocol/nearcore#758]
We send PayloadRequest to the original proposer, but if he went offline we will never get the payload and no one will make progress

**Comment by mfornet** [comment]
The simplest workaround, in this case, is sending the request to the sender of the message instead of the original proposer. Was there any particular reason not to do that in the first place?

Another advantage of requesting message to current sender instead of the original proposer is that if authority with the highest id has poor connection (high latency) performance decrease. We force `O(n)` messages being passed between peers with high latencies.

**Comment by nearmax** [comment]
In general, whoever sends us any network message should be fully responsible for its content. That's how it was with TxFlow for instance, where we would fetch the entire sub-DAG from the sender of its root even if some of the messages were originally produced and signed by other peers.

**Comment by mfornet** [comment]
Closing this after #767
