### ISSUE TITLE
encode_message should take reference

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#794]
`encode_message` should not take ownership of the message but ownership instead. When messages are wrapped into `Arc` clone is needed before encoding which is a performance problem. See #792 for details and discussion.

Right now messages are cloned all the time before being encoded to send it over the network.

**Comment by nearmax** [comment]
The core problem is in the way we implement `From`. It should be using reference:
```
From<&Message> for network_proto::Message
```

**Comment by bowenwang1996** [comment]
Then we are cloning inside `From`, which is not desirable.

**Comment by nearmax** [comment]
Why would it not be desirable?

We cannot avoid not cloning at all, because we are literally constructing a new struct when we a converting Rust struct to a proto struct. However, there might be a slight optimization that we can make in the future. There is not exact 1:1 matching, and when proto struct is constructed it should decide inside what should be cloned or copied or not used at all. So cloning inside is more optimal than cloning outside.

**Comment by bowenwang1996** [comment]
We do not clone (in most cases) when converting a Rust struct to a proto struct. I think move happens there.

**Comment by nearmax** [comment]
Ok

**Comment by mfornet** [comment]
@nearmax Why closing, are we cloning every time while sending through the network? Maybe we can have `encode_message` and `encode_ref_message`.

**Comment by nearmax** [comment]
In order to construct a network message we take a regular Rust struct and deconstruct it by moving or copying some of its fields, which is completely normal and in fact efficient for a general situation when there are no proxies.

With proxies that duplicate the messages they would have to clone the Rust struct and construct protos from them via deconstruction.
