### ISSUE TITLE
#781 broke some stability of alphanet with >4 nodes

### ISSUE THREAD

**Issue by mikhailOK** [nearprotocol/nearcore#817]
to reproduce run test_7_10_multiple_nodes from test_alphanet

```
---- test_7_10_multiple_nodes stdout ----
TRIAL #0
TRIAL #1
TRIAL #2
BBBB Slept 61000; max_wait_ms 60000
thread 'test_7_10_multiple_nodes' panicked at 'Timed out waiting for the condition', test-utils/testlib/src/alphanet_utils.rs:457:13
```

**Comment by nearmax** [comment]
The following integration test verifies stability of our network with 7 nodes: https://github.com/nearprotocol/nearcore/blob/master/tests/test_alphanet.rs#L64
We disabled it because we had interference of integration tests that @mikhailOK  was solving. Now that interference is addressed we re-enabled it and discovered that it is broken. Doing a binary search on PRs I found out that #781 introduced the breakage. 
To verify, checkout 312fe85540783b336b4570e594488d2058d5c902 and verify that test does not break. Then checkout b57d4a56e523df3b728ca766cfffde5b285771d5 and verify that the test breaks. CC-ing @ilblackdragon and @mfornet who worked on the PR.
