### ISSUE TITLE
RFC Crypto code consolidation

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#833]
Our crypto code is inefficient from perspective of speed and design.

Performance:
- [ ] All our keys are fixed size. We should be used fixed sized byte arrays instead of vectors and pass references to arrays instead of references to slices where it is possible to avoid reconstruction of arrays from slices. Currently, we are re-constructing vectors of bytes where we should be just passing reference to an array.
- [ ] We should be using LRU for: verification, signing, aggregation and hashing;
- [ ] The size of LRU cache should be calculated from the size of the objects and instead of eyeballed.

Design:
- [ ] We have exactly two types of signatures in our code: BLS and ED25519. However we implement several abstractions: `GroupSignature` and `AggregateSignature`. These might be unified;
- [ ] We use the same naming scheme for keys, and signatures for both BLS and ED25519. We should revisit if this is what we want;
- [ ] There is no need to declare our own `ToBytes` trait, it is perfectly expressible with `From` trait;
- [ ] I am not sure we are following the serde API in serialization code. Someone should read https://serde.rs and revisit our code.

Big question, open for discussion (cc @ilblackdragon , @evgenykuzyakov , @janedegtiareva , and @vgrichina , since it involves cross-language/platform compatibility):
- [ ] Currently we compute hash of any object by first serializing it and then computing hash on the underlying serialized data. This is cross-compatible assuming we stick with proto and bs58 serialization, however serialization is not meant to be used for hashing and it allocates two temporary objects in addition to the Rust struct that we are hashing (one is the proto version of the Rust struct, another one is its bytes representation https://github.com/nearprotocol/nearcore/blob/master/core/primitives/src/transaction.rs#L552) . The alternative is to use the standard way of hashing a struct in Rust, that employs a visitor pattern (https://doc.rust-lang.org/std/hash/trait.Hash.html) where we visit fields of the struct in DFS manner and keep only the necessary data in RAM. The alternative is however slightly harder to spec-out to make it cross-platform.
We should benchmark both methods and if the alternative hashing is significantly faster decide if we want to trade the cross-platform complexity.

**Comment by ilblackdragon** [comment]
I'm actually unclear if caching ED signature verification make sense - it's fast enough and with cache it's going to be all over the place. But I guess some metrics would be good here.

For now we disabled BLS, I'm keeping it around just because it's quite a hard thing to integrate so want to keep it for future compilable instead of restoring it later.

We are planning to add alternative curves support (at least ECDSA).

I'm highly against visitor pattern for hashing. Hashing bytes of the object is the standard practice, and following standards is the goal. Instead we should make sure we don't need to serialize more than once to compute hash and send/receive data. This way will give us the same performance.

**Comment by ilblackdragon** [comment]
#1215 cleans up the crypto code and moves it into separate cargo.
Still not sure about LRU stuff, so let's close this and revisit optimizations separately.
